using Marketplace.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Marketplace.Infrastructure.Persistence.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260707140000_FixReturnRequestIdIdentity")]
public partial class FixReturnRequestIdIdentity : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            DO $$
            BEGIN
              IF EXISTS (
                SELECT 1 FROM information_schema.tables
                WHERE table_schema = 'public' AND table_name = 'return_requests'
              ) AND NOT EXISTS (
                SELECT 1
                FROM pg_attribute a
                JOIN pg_class c ON c.oid = a.attrelid
                JOIN pg_namespace n ON n.oid = c.relnamespace
                WHERE n.nspname = 'public'
                  AND c.relname = 'return_requests'
                  AND a.attname = 'Id'
                  AND NOT a.attisdropped
                  AND a.attidentity IN ('a', 'd')
              ) THEN
                ALTER TABLE return_requests ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;
              END IF;
            END $$;
            """);

        migrationBuilder.Sql(
            """
            DO $$
            BEGIN
              IF EXISTS (
                SELECT 1 FROM information_schema.tables
                WHERE table_schema = 'public' AND table_name = 'return_items'
              ) AND NOT EXISTS (
                SELECT 1
                FROM pg_attribute a
                JOIN pg_class c ON c.oid = a.attrelid
                JOIN pg_namespace n ON n.oid = c.relnamespace
                WHERE n.nspname = 'public'
                  AND c.relname = 'return_items'
                  AND a.attname = 'Id'
                  AND NOT a.attisdropped
                  AND a.attidentity IN ('a', 'd')
              ) THEN
                ALTER TABLE return_items ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;
              END IF;
            END $$;
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
    }
}
